; The red tracker Dev Board with the WM1110 module
; Using experimental InkHUD UI (work in progress)
[platformio]
extra_configs = src/graphics/niche/InkHUD/PlatformioConfig.ini

[env:wio-tracker-wm1110-eink]
extends = nrf52840_base, inkhud
;board_check = true
board = wio-tracker-wm1110
build_flags = 
  ${nrf52840_base.build_flags}
  ${inkhud.build_flags}
  -Ivariants/wio-tracker-wm1110-eink
  -Isrc/platform/nrf52/softdevice
  -Isrc/platform/nrf52/softdevice/nrf52
  -DWIO_WM1110
  -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m4/fpv4-sp-d16-hard"
  -DGPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = 
  ${nrf52_base.build_src_filter}
  ${inkhud.build_src_filter}
  +<../variants/wio-tracker-wm1110-eink>
lib_deps = 
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot intead of AdafruitGFX
  ${nrf52840_base.lib_deps}
; If not set we will default to uploading over serial (first it forces bootloader entry by talking 1200bps to cdcacm)
upload_protocol = nrfutil
